//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box_Offic
    {
        public int id_ticket { get; set; }
        public int id_flight { get; set; }
        public int id_employee { get; set; }
        public int id_passenger { get; set; }
        public Nullable<int> id_discount { get; set; }
        public System.DateTime date_of_sale { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Discounts Discounts { get; set; }
        public virtual Flights Flights { get; set; }
        public virtual Passengers Passengers { get; set; }
    }
}
